name: pr merge

on:
  workflow_call:
    inputs:  
      autoMerge:
        description: 'Auto merge pr'
        default: false
        required: false
        type: boolean

jobs:
  auto-merge:
    if: ${{ inputs.autoMerge }}
    uses: onecx/ci-common/.github/workflows/helm-pr-auto-merge.yaml@v1
    secrets: inherit