name: build

on:
  workflow_call:
  
jobs:
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    with:
      push: true
      artifact: ''    
      helmdir: 'helm'
      helmAbsoluteDir: true
      templateValuesYaml: 'product.version={{ .Version }},product.name={{ .Name }}'